import { colors } from '../colors';

export const mainStyles = {
    container: {
        padding: '1rem',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1rem',
    },
    title: {
        color: colors.text.primary,
        textAlign: 'center' as const,
        marginBottom: '1rem',
        fontSize: 'clamp(1.5rem, 3vw, 2rem)',
    },
    mapGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '1rem',
    },
    mapCard: {
        background: colors.background.card,
        border: `1px solid ${colors.border.medium}`,
        borderRadius: '12px',
        padding: '1rem',
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        gap: '0.5rem',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    lockedMapCard: {
        background: colors.background.dark,
        border: `1px solid ${colors.border.light}`,
        cursor: 'not-allowed',
    },
    mapIcon: {
        fontSize: '3rem',
    },
    mapName: {
        color: colors.text.primary,
        margin: 0,
        fontSize: 'clamp(1.1rem, 2vw, 1.3rem)',
    },
    mapDescription: {
        color: colors.text.secondary,
        textAlign: 'center' as const,
        margin: 0,
        fontSize: 'clamp(0.9rem, 1.8vw, 1.1rem)',
    },
    lockedText: {
        color: colors.text.disabled,
        fontSize: '0.9rem',
        marginTop: '0.5rem',
    },
    stageSelect: {
        container: {
            width: '100%',
            height: '100%',
            display: 'flex',
            flexDirection: 'column' as const,
            alignItems: 'center',
            padding: '1rem',
            boxSizing: 'border-box' as const,
            overflowX: 'hidden' as const,
        },
        content: {
            width: '100%',
            maxWidth: '1200px',
            height: '100%',
            display: 'flex',
            flexDirection: 'column' as const,
            gap: '1rem',
            padding: '0.5rem',
            boxSizing: 'border-box' as const,
        },
        header: {
            width: '100%',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: '0.5rem',
            boxSizing: 'border-box' as const,
        },
        grid: {
            flex: 1,
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: '1rem',
            width: '100%',
            padding: '0.5rem',
            boxSizing: 'border-box' as const,
        },
        footer: {
            width: '100%',
            display: 'flex',
            justifyContent: 'center',
            padding: '0.5rem',
            boxSizing: 'border-box' as const,
        },
        card: {
            background: colors.background.card,
            border: `1px solid ${colors.border.medium}`,
            borderRadius: '12px',
            padding: '1.5rem',
            cursor: 'pointer',
            transition: 'all 0.3s ease',
            display: 'flex',
            flexDirection: 'column' as const,
            gap: '1rem',
        },
        cardHover: {
            transform: 'translateY(-4px)',
            background: colors.background.light,
            boxShadow: colors.shadow.medium,
        },
        cardName: {
            fontSize: 'clamp(1.1rem, 2vw, 1.5rem)',
            fontWeight: 600,
            color: colors.text.primary,
            margin: 0,
        },
        cardDifficulty: {
            fontSize: 'clamp(0.8rem, 1.5vw, 1rem)',
            color: colors.text.secondary,
            margin: 0,
        },
        cardDescription: {
            fontSize: 'clamp(0.9rem, 1.8vw, 1.1rem)',
            color: colors.text.secondary,
            margin: 0,
            lineHeight: 1.4,
        },
    },
} as const;
